[custom.flox]
command = 'echo $FLOX_PROMPT_ENVIRONMENTS'
description = 'The currently active flox environments'
when = ''' [ -n "${FLOX_PROMPT_ENVIRONMENTS:-}" ] '''
style = 'bold 216'
format = 'in [($output)]($style) '
